apiVersion: batch/v1
kind: Job
metadata:
  name: solr-create-collection
spec:
#  selector:
#    matchLabels:
#      app: solr-create-collection # has to match .spec.template.metadata.labels
#  replicas: 1
  template:
    metadata:
      labels:
        app: solr-create-collection
    spec:
      containers:
      - name: solr-create-collection
        imagePullPolicy: Always
        image: nexusjpl/solr-cloud-init:1.0.1
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.25"
        env:
        - name: MINIMUM_NODES
          value: "{{ .Values.solr.replicaCount }}"
        - name: SOLR_HOST
          value: "{{ .Release.Namespace }}-solr-svc"
        - name: SDAP_SOLR_URL
          value: "http://$(SOLR_HOST):8983/solr/"
        - name: SDAP_ZK_SOLR
          value: "{{ .Release.Namespace }}-zookeeper:2181/solr"
        - name: CREATE_COLLECTION_PARAMS
          value: "name=nexustiles&numShards=$(MINIMUM_NODES)&waitForFinalState=true"
      restartPolicy: OnFailure
